[package]
name = "section02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#▼リスト5-1
eframe = "0.21.0"
egui = "0.21.0"